package org.little.http.app.file;

import java.util.Date;

import org.little.http.handler.lHttpResponse;
import org.little.http.handler.lHttpRequest;
//import org.little.util.Logger;
//import org.little.util.LoggerFactory;
import io.netty.channel.ChannelHandlerContext;

public class HttpFileResponse extends lHttpResponse{
//       private static final Logger  logger = LoggerFactory.getLogger(HttpFileResponse.class);
	    private static String d=""
			+"MIII1zCCCIKgAwIBAgIQQFAXsNJia97B7Xx2XFwA2jAMBggqhQMHAQEDAgUAMHkxEjAQBgoJkiaJ"
			+"k/IsZAEZFgJydTETMBEGCgmSJomT8ixkARkWA2NicjEWMBQGCgmSJomT8ixkARkWBnJlZ2lvbjEM"
			+"MAoGA1UECxMDUEtJMQ4wDAYDVQQLEwVHVUJaSTEYMBYGA1UEAxMPUk9PVHN2Yy1DQS10ZXN0MB4X"
			+"DTE5MDIwNzA5NTY0NVoXDTM1MDUwNDIzNTkwMFowezESMBAGCgmSJomT8ixkARkWAnJ1MRMwEQYK"
			+"CZImiZPyLGQBGRYDY2JyMRYwFAYKCZImiZPyLGQBGRYGcmVnaW9uMRIwEAYDVQQLEwlUYXRhcnN0"
			+"YW4xDDAKBgNVBAsTA1BLSTEWMBQGA1UEAxMNOTJzdmMtQ0EtdGVzdDBmMB8GCCqFAwcBAQEBMBMG"
			+"ByqFAwICIwEGCCqFAwcBAQICA0MABEBRMaqF0iAEez5Otfz1XUC9qWkVKGAjdUOVJnJegOCfqmpN"
			+"/wrSXJPojhcT7TfmZx4qvh7OjnmpiYPWh+y8HQNLo4IG2TCCBtUwgbgGCSsGAQQBnFYEDwSBqjCB"
			+"p4AU6T1BXNyIQwvWMqVz84qxC7YdeM+hfaR7MHkxEjAQBgoJkiaJk/IsZAEZFgJydTETMBEGCgmS"
			+"JomT8ixkARkWA2NicjEWMBQGCgmSJomT8ixkARkWBnJlZ2lvbjEMMAoGA1UECxMDUEtJMQ4wDAYD"
			+"VQQLEwVHVUJaSTEYMBYGA1UEAxMPUk9PVHN2Yy1DQS10ZXN0ghBANhC30yJWuQvsFzhRZ8ouMB0G"
			+"A1UdDgQWBBTt42bjUFGiGPZ6XFIMJj5/I9Cg3TCBuAYJKwYBBAHQBAQGBIGqMIGngBSi6BTIG8yB"
			+"+elKEcNJlXdZ8HkUFqF9pHsweTESMBAGCgmSJomT8ixkARkWAnJ1MRMwEQYKCZImiZPyLGQBGRYD"
			+"Y2JyMRYwFAYKCZImiZPyLGQBGRYGcmVnaW9uMQwwCgYDVQQLEwNQS0kxDjAMBgNVBAsTBUdVQlpJ"
			+"MRgwFgYDVQQDEw9ST09Uc3ZjLUNBLXRlc3SCEEBQFMBDpXWTXUPmKlp6y4gwKAYJKwYBBAHQBAQD"
			+"BBswGQYJKwYBBAHQBAUDBAwyMzgwVEgzNVIxMDEwWAYFKoUDZG8ETwxN0JDQn9CaICLQodGA0LXQ"
			+"tNGB0YLQstC+INCa0JfQmCDQodCa0JDQlCAi0KHQuNCz0L3QsNGC0YPRgNCwIiIg0LLQtdGA0YHQ"
			+"uNGPIDUwCwYDVR0PBAQDAgGGMHYGA1UdEQRvMG2gSgYDVQQKoEMMQdCe0YLQtNC10LvQtdC90LjQ"
			+"tSAtINCd0JEg0KDQtdGB0L/Rg9Cx0LvQuNC60LAg0KLQsNGC0LDRgNGB0YLQsNC9oB8GA1UEDaAY"
			+"DBbQodC10YDQuNGPINCY0JDQoSDQojA3MCsGA1UdEAQkMCKADzIwMTkwMjA3MDk1NjQ1WoEPMjAy"
			+"MDA1MDQyMzU5MDBaMBAGCSsGAQQB0AQECwQDAgEBMIHVBggrBgEFBQcBAQSByDCBxTBaBggrBgEF"
			+"BQcwAoZObGRhcDovL3JlZ2lvbi5jYnIucnUvQ049Uk9PVHN2Yy1DQS10ZXN0LE9VPUdVQlpJLE9V"
			+"PVBLSSxEQz1yZWdpb24sREM9Y2JyLERDPXJ1MGcGCCsGAQUFBzAChltsZGFwOi8vcmVnaW9uLmNi"
			+"ci5ydS9DTj1ST09Uc3ZjLUNBLTU2MDFJUENUNU4wMS10ZXN0LE9VPUdVQlpJLE9VPVBLSSxEQz1y"
			+"ZWdpb24sREM9Y2JyLERDPXJ1MIGyBgNVHSMEgaowgaeAFEH+BGZ+4g6vtPMfo7uEiXcUwYltoX2k"
			+"ezB5MRIwEAYKCZImiZPyLGQBGRYCcnUxEzARBgoJkiaJk/IsZAEZFgNjYnIxFjAUBgoJkiaJk/Is"
			+"ZAEZFgZyZWdpb24xDDAKBgNVBAsTA1BLSTEOMAwGA1UECxMFR1VCWkkxGDAWBgNVBAMTD1JPT1Rz"
			+"dmMtQ0EtdGVzdIIQQFAXsAthaGZpfvSsXFgEijAPBgNVHRMECDAGAQH/AgEAMIIBIgYFKoUDZHAE"
			+"ggEXMIIBEwxN0JDQn9CaICLQodGA0LXQtNGB0YLQstC+INCa0JfQmCDQodCa0JDQlCAi0KHQuNCz"
			+"0L3QsNGC0YPRgNCwIiIg0LLQtdGA0YHQuNGPIDUMP9CQ0J/QmiAi0KHQuNCz0L3QsNGC0YPRgNCw"
			+"LdGB0LXRgNGC0LjRhNC40LrQsNGCIiDQstC10YDRgdC40Y8gNQxU0JLRi9C/0LjRgdC60LAg0LjQ"
			+"tyDQl9Cw0LrQu9GO0YfQtdC90LjRjyDihJYxNDkvMy8yLzItMTAyMiDQvtGCIDMwINC40Y7QvdGP"
			+"IDIwMTUg0LMuDCvQodCkLzEyOC0yNzQ2INC+0YIgMTcg0L3QvtGP0LHRgNGPIDIwMTUg0LMuMIHE"
			+"BgNVHR8EgbwwgbkwVKBSoFCGTmxkYXA6Ly9yZWdpb24uY2JyLnJ1L0NOPVJPT1RzdmMtQ0EtdGVz"
			+"dCxPVT1HVUJaSSxPVT1QS0ksREM9cmVnaW9uLERDPWNicixEQz1ydTBhoF+gXYZbbGRhcDovL3Jl"
			+"Z2lvbi5jYnIucnUvQ049Uk9PVHN2Yy1DQS01NjAxSVBDVDVOMDEtdGVzdCxPVT1HVUJaSSxPVT1Q"
			+"S0ksREM9cmVnaW9uLERDPWNicixEQz1ydTBrBgNVHRIEZDBioD8GA1UECqA4DDbQmtC+0YDQvdC1"
			+"0LLQvtC5INCm0KEg0JTQkdCR0KAg0JHQsNC90LrQsCDQoNC+0YHRgdC40LigHwYDVQQNoBgMFtCh"
			+"0LXRgNC40Y8g0JjQkNChINCiMDcwDAYIKoUDBwEBAwIFAANBAOX7FXqYWJrcrDh4eP7q7S5yKTa5"
			+"mHK3dDT8ZuLgKK6zBXdsZXphfWScQToXvjkn6N6M9F2WNzbtMu/p2jYXF/M="              
			;

       //public void sevaUploadFile(ChannelHandlerContext ctx,HttpFileRequest req) {
       //       getFile(ctx,req,"/redirect.html");
       //}
       public void getTest1(ChannelHandlerContext ctx,lHttpRequest req){
               byte [] filebuffer=d.getBytes();
               getFile(ctx,req,"test.log",filebuffer,new Date(), false);

       }

}

 
